In [2]:
# example of loading the keras facenet model
from keras.models import load_model
# load the model
model = load_model('/Users/bildad.namawa/sandbox/jupyter-notebooks/facenet-keras/facenet_keras.h5')
# summarize input and output shape
print(model.inputs)
print(model.outputs)

Using TensorFlow backend.


W0820 01:59:45.452542 4390725056 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.



W0820 01:59:45.522304 4390725056 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



W0820 01:59:45.540260 4390725056 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:245: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



W0820 01:59:45.540963 4390725056 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.



W0820 01:59:45.541432 4390725056 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



W0820 01:59:45.587236 4390725056 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:1834: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.



W0820 01:59:45.843103 4390725056 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



W0820 01:59:54.787698 4390725056 deprecation.py:506] From //anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


[<tf.Tensor 'input_1:0' shape=(?, 160, 160, 3) dtype=float32>]
[<tf.Tensor 'Bottleneck_BatchNorm/cond/Merge:0' shape=(?, 128) dtype=float32>]


//anaconda3/lib/python3.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [3]:
# confirm mtcnn was installed correctly
import mtcnn
# print version
print(mtcnn.__version__)

0.0.9


[[[12 13 15]
  [12 13 15]
  [12 13 15]
  ...
  [ 8  8 10]
  [ 7  7  9]
  [ 7  7  9]]

 [[12 13 15]
  [12 13 15]
  [12 13 15]
  ...
  [ 8  8 10]
  [ 7  7  9]
  [ 7  7  9]]

 [[12 13 15]
  [12 13 15]
  [12 13 15]
  ...
  [ 8  8 10]
  [ 7  7  9]
  [ 7  7  9]]

 ...

 [[ 7  7  7]
  [ 7  7  7]
  [ 7  7  7]
  ...
  [10 10 12]
  [10 10 12]
  [ 9  9 11]]

 [[ 7  7  7]
  [ 7  7  7]
  [ 7  7  7]
  ...
  [10 10 12]
  [10 10 12]
  [ 9  9 11]]

 [[ 7  7  7]
  [ 7  7  7]
  [ 7  7  7]
  ...
  [10 10 12]
  [10 10 12]
  [ 9  9 11]]]


In [1]:
# create the detector, using default weights


# load image from file
from PIL import Image
from numpy import asarray

image = Image.open('/Users/bildad.namawa/sandbox/jupyter-notebooks/facenet-keras/image.jpg')
# convert to RGB, if needed
image = image.convert('RGB')
# convert to array
pixels = asarray(image)
print(pixels)

from mtcnn.mtcnn import MTCNN
print("yes")
detector = MTCNN()
# detect faces in the image
print("yes 2")
results = detector.detect_faces(pixels)
print("yes 3")
print(results)

[[[12 13 15]
  [12 13 15]
  [12 13 15]
  ...
  [ 8  8 10]
  [ 7  7  9]
  [ 7  7  9]]

 [[12 13 15]
  [12 13 15]
  [12 13 15]
  ...
  [ 8  8 10]
  [ 7  7  9]
  [ 7  7  9]]

 [[12 13 15]
  [12 13 15]
  [12 13 15]
  ...
  [ 8  8 10]
  [ 7  7  9]
  [ 7  7  9]]

 ...

 [[ 7  7  7]
  [ 7  7  7]
  [ 7  7  7]
  ...
  [10 10 12]
  [10 10 12]
  [ 9  9 11]]

 [[ 7  7  7]
  [ 7  7  7]
  [ 7  7  7]
  ...
  [10 10 12]
  [10 10 12]
  [ 9  9 11]]

 [[ 7  7  7]
  [ 7  7  7]
  [ 7  7  7]
  ...
  [10 10 12]
  [10 10 12]
  [ 9  9 11]]]


W0820 07:44:53.632463 4685497792 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/mtcnn/mtcnn.py:187: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



W0820 07:44:53.662994 4685497792 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/mtcnn/mtcnn.py:193: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



W0820 07:44:53.688882 4685497792 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/mtcnn/network.py:43: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.



W0820 07:44:53.689904 4685497792 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/mtcnn/layer_factory.py:88: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.



W0820 07:44:53.693724 4685497792 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/mtcnn/layer_factory.py:79: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.



W0820 07:44:53.694793 4685497792 deprecation.py:506] From //anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


W0820 07:44:53.729022 4685497792 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/mtcnn/layer_factory.py:171: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



W0820 07:44:53.804033 4685497792 deprecation.py:323] From //anaconda3/lib/python3.7/site-packages/mtcnn/layer_factory.py:221: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.


yes


W0820 07:44:54.157192 4685497792 deprecation_wrapper.py:119] From //anaconda3/lib/python3.7/site-packages/mtcnn/layer_factory.py:196: The name tf.nn.xw_plus_b is deprecated. Please use tf.compat.v1.nn.xw_plus_b instead.



yes 2


In [1]:
# extract the bounding box from the first face
x1, y1, width, height = results[0]['box']
# bug fix
x1, y1 = abs(x1), abs(y1)
x2, y2 = x1 + width, y1 + height

NameError: name 'results' is not defined

In [25]:
# extract the face
face = pixels[y1:y2, x1:x2]

In [25]:
# resize pixels to the model size
image = Image.fromarray(face)
image = image.resize((160, 160))
face_array = asarray(image)

In [25]:
# function for face detection with mtcnn
from PIL import Image
from numpy import asarray
from mtcnn.mtcnn import MTCNN

# extract a single face from a given photograph
def extract_face(filename, required_size=(160, 160)):
	# load image from file
	image = Image.open(filename)
	# convert to RGB, if needed
	image = image.convert('RGB')
	# convert to array
	pixels = asarray(image)
	# create the detector, using default weights
	detector = MTCNN()
	# detect faces in the image
	results = detector.detect_faces(pixels)
	# extract the bounding box from the first face
	x1, y1, width, height = results[0]['box']
	# bug fix
	x1, y1 = abs(x1), abs(y1)
	x2, y2 = x1 + width, y1 + height
	# extract the face
	face = pixels[y1:y2, x1:x2]
	# resize pixels to the model size
	image = Image.fromarray(face)
	image = image.resize(required_size)
	face_array = asarray(image)
	return face_array

# load the photo and extract the face
pixels = extract_face('...')

FileNotFoundError: [Errno 2] No such file or directory: '...'